# Case does not matter
# Adapted and extended from: https://github.com/HanssonMagnus/scrape_bis/blob/main/source/0_scrape_bis/constants.py
central_bank_mapping = {
                "Bank Indonesia" : "Bank Indonesia",
                "Bank of Indonesia" : "Bank Indonesia",
                "Bank of Albania" : "Bank of Albania",
                "Bank of Algeria" : "Bank of Algeria",
                "Bank of Botswana" : "Bank of Botswana",
                "Bank of Canada" : "Bank of Canada",
                "Bank of England" : "Bank of England",
                "Bank of Estonia" : "Bank of Estonia",
                "Bank of Finland" : "Bank of Finland",

                "Bank of Ghana" : "Bank of Ghana",
                "Bank of Greece" : "Bank of Greece",
                "Bank of Guatemala" : "Bank of Guatemala",
                "Bank of Guyana" : "Bank of Guyana",
                "Bank of Israel" : "Bank of Israel",
                "Bank of Italy" : "Bank of Italy",
                "Baml of Italy" : "Bank of Italy",

                "Bank of Jamaica" : "Bank of Jamaica",
                "Bank of Japan" : "Bank of Japan",
                "Bank of Korea" : "Bank of Korea",
                "Bank of Latvia" : "Bank of Latvia",
                "Bank of Lativa" : "Bank of Latvia",
                "Bank of Lithuania" : "Bank of Lithuania",
                "Bank of Mauritius" : "Bank of Mauritius",
                "Bank of Mexico" : "Bank of Mexico",
                "Bank of Morocco" : "Bank of Morocco",
                "Bank Al-Maghrib" : "Bank of Morocco",
                "Bank of Mozambique" : "Bank of Mozambique",
                "Bank of Namibia" : "Bank of Namibia",
                "Bank of Papua New Guinea" : "Bank of Papua New Guinea",
                "Bank of Portugal" : "Bank of Portugal",
                "Banco de Portugal" : "Bank of Portugal",
                "Bank of Sierra Leone" : "Bank of Sierra Leone",
                "Bank of Slovenia" : "Bank of Slovenia",
                "Bank of Spain" : "Bank of Spain",
                "Banco de España" : "Bank of Spain",
                "Bank of Tanzania" : "Bank of Tanzania",
                "Bank of Thailand" : "Bank of Thailand",
                "Bank of Uganda" : "Bank of Uganda",
                "Bank of the Uganda" : "Bank of Uganda",
                "Bank of Zambia" : "Bank of Zambia",
                "Bank of the Netherlands Antilles" : "Bank of the Netherlands Antilles",
                "Bank van de Nederlandse Antillen" : "Bank of the Netherlands Antilles",

                "Board of Governors of the Federal Reserve System" : "board of governors of the federal reserve system",
                "Board of Governors of the US Federal Reserve System" : "board of governors of the federal reserve system",
                "Board of the US Federal Reserve System"  : "board of governors of the federal reserve system",
                "Board of Governors of the US Federal Reserve"  : "board of governors of the federal reserve system",
                "Governors of the U.S. Federal Reserve System" : "board of governors of the federal reserve system",
                "Board of the U S Federal Reserve System" : "board of governors of the federal reserve system",
                "US Federal Reserve System" : "board of governors of the federal reserve system",
                "Board of Governors of the federal reserve" : "board of governors of the federal reserve system",
                "Board of governors of the us fed" : "board of governors of the federal reserve system",
                "Board of Governors of the US Fed" : "board of governors of the federal reserve system",
                "Federal Reserve System" : "board of governors of the federal reserve system",
                "Federal Reserve Board" : "board of governors of the federal reserve system",
                "Bd. of Govnrs. of the US Fed. Res. System" : "board of governors of the federal reserve system",
                "Board of Governors of the US Federal Reserve" : "board of governors of the federal reserve system",
                "US Federal Reserve" : "board of governors of the federal reserve system",

                "Inter-American Development Bank" : "inter-american development bank",

                "Sveriges Riksbank" : "sveriges riksbank",
                "Sveriges Risksbank" : "sveriges riksbank",
                "Sveriges Riskbank" : "sveriges riksbank",
                "Bank of Sweden" : "sveriges riksbank",
                "Swedish Central Bank" : "sveriges riksbank",
                "Swedish Riskbank" :"sveriges riksbank",

                "Central Bank of the Republic of Austria" : "central bank of the republic of austria",
                "Austrian National Bank" : "central bank of the republic of austria",
                "Oesterreichische Nationalbank"  : "central bank of the republic of austria",
                "Austrian Nationalbank"  : "central bank of the republic of austria",

                "ECB" : "european central bank",
                "European Central Bank" : "european central bank",
                "European Central, Bank" : "european central bank",
                "Europ. Central Bank" : "european central bank",

                "Bulgarian National Bank" : "Bulgarian National Bank",
                "Central Bank of Argentina" : "Central Bank of Argentina",
                "Central Bank of Aruba" : "Central Bank of Aruba",
                "Central Bank of Bahrain" : "Central Bank of Bahrain",
                "Bahrain Monetary Agency" : "Central Bank of Bahrain",
                "Central Bank of Barbados" : "Central Bank of Barbados",
                "Central Bank of Belize" : "Central Bank of Belize",
                "Central Bank of Bolivia" : "Central Bank of Bolivia",
                "Central Bank of Bosnia and Herzegovina" : "Central Bank of Bosnia and Herzegovina",
                "Central Bank of Brazil" : "Central Bank of Brazil",
                "Central Bank of Chile" : "Central Bank of Chile",
                "Central Bank of Colombia" : "Central Bank of Colombia",
                "Banco de la República" : "Central Bank of Colombia",
                "Central Bank of Ecuador" : "Central Bank of Ecuador",
                "Central Bank of Curaçao and Sint Maarten" : "Central Bank of Curaçao and Sint Maarten",
                "Centrale Bank van Curaçao en Sint Maarten" : "Central Bank of Curaçao and Sint Maarten",
                "Central Bank of Curacao and Sint Maarten" : "Central Bank of Curaçao and Sint Maarten",
                "Central Bank of Armenia" : "Central Bank of Armenia",

                "Central Bank of Cyprus" : "Central Bank of Cyprus",
                "Central Bank of Iceland" : "Central Bank of Iceland",
                "Central Bank of Ireland" : "central bank of ireland",
                "Central Bank of Irelnad" : "central bank of ireland",
                "Central Bank of The Gambia" : "central bank of gambia",
                "Central Bank of Gambia" : "central bank of gambia",
                "Authority of Ireland" : "central bank of ireland",
                "Central Bank of Jordan" : "Central Bank of Jordan",
                "Central Bank of Kenya" : "Central Bank of Kenya",
                "Central Bank of Kuwait" : "Central Bank of Kuwait",
                "Central Bank of Luxembourg" : "Central Bank of Luxembourg",
                "Central Bank of Malaysia" : "Central Bank of Malaysia",
                "Bank of Malaysia" : "Central Bank of Malaysia",
                "CB of Malaysia" : "Central Bank of Malaysia",
                "Bank Negara Malaysia" : "Central Bank of Malaysia",
                "Central Bank of Malta" : "Central Bank of Malta",
                "Central Bank of Nepal" : "Central Bank of Nepal",
                "Central Bank of Nigeria" : "Central Bank of Nigeria",
                "norges bank" : "Central Bank of Norway",
                "Central Bank of Norway" : "Central Bank of Norway",
                "Central Bank of Samoa" : "Central Bank of Samoa",
                "Central Bank of Seychelles" : "Central Bank of Seychelles",
                "Central Bank of Solomon Islands" : "Central Bank of Solomon Islands",
                "Central Bank of Sri Lanka" : "Central Bank of Sri Lanka",
                "Central Bank of The Bahamas" : "Central Bank of The Bahamas",
                "Central Bank of Trinidad and Tobago" : "Central Bank of Trinidad and Tobago",
                "Central Bank of Trinidad" : "Central Bank of Trinidad and Tobago",
                "Central Bank of Uruguay" : "Central Bank of Uruguay",
                "central bank of the Philippines" : "central bank of the Philippines",
                "Bangko Sentral ng Pilipinas" : "central bank of the Philippines",
                "Central Bank of the Republic of Kosovo" : "Central Bank of the Republic of Kosovo",
                "Bank of Russia" : "Bank of Russia",
                "Central Bank of the Russian Federation" : "Bank of Russia",
                "Central Bank of the United Arab Emirates" : "Central Bank of the United Arab Emirates",
                "Croatian National Bank" : "Croatian National Bank",
                "Croation National Bank" : "Croatian National Bank",
                "Czech National Bank" : "Czech National Bank",
                "National Bank of Denmark" : "National Bank of Denmark",
                "Danmarks National Bank" : "National Bank of Denmark",
                "Danmarks Nationalbank" : "National Bank of Denmark",
                "Deutsche Bundesbank" : "Deutsche Bundesbank",
                "Cayman Islands Monetary Authority" : "Cayman Islands Monetary Authority",
                "Eastern Caribbean Central Bank" : "Eastern Caribbean Central Bank",
                "Federal Reserve Bank of Atlanta" : "Federal Reserve Bank of Atlanta",
                "Federal Reserve Bank of Boston" : "Federal Reserve Bank of Boston",
                "Federal Reserve Bank of Chicago" : "Federal Reserve Bank of Chicago",
                "Federal Reserve Bank of Dallas" : "Federal Reserve Bank of Dallas",
                "Federal Reserve Bank of Kansas City" : "Federal Reserve Bank of Kansas City",
                "Federal Reserve Bank of Minneapolis" : "Federal Reserve Bank of Minneapolis",
                "Federal Reserve Bank of New York" : "Federal Reserve Bank of New York",
                "Fed. Res. Bank of New York" : "Federal Reserve Bank of New York",
                "Federal Reserve Bank of Philadelphia" : "Federal Reserve Bank of Philadelphia",
                "Federal Reserve Bank of Richmond" : "Federal Reserve Bank of Richmond",
                "Federal Reserve Bank of San Francisco" : "Federal Reserve Bank of San Francisco",
                "Hong Kong Monetary Authority" : "hong kong monetary authority",
                "Hong Kong Monetary" : "hong kong monetary authority",
                "Hong Kong Mon. Authority" : "hong kong monetary authority",
                "central bank of Hungary" : "central bank of Hungary",
                "Magyar Nemzeti Bank" : "central bank of Hungary",
                "Maldives Monetary Authority" : "Maldives Monetary Authority",
                "Monetary Authority of Macao" : "Monetary Authority of Macao",
                "Mon. Authority of Macao" : "Monetary Authority of Macao",
                "Monetary Authority of Singapore" : "Monetary Authority of Singapore",
                "National Bank of Belgium" : "National Bank of Belgium",
                "National Bank of Cambodia" : "National Bank of Cambodia",
                "National Bank of Romania" : "National Bank of Romania",
                "National Bank of Serbia" : "National Bank of Serbia",
                "National Bank of Slovakia" : "National Bank of Slovakia",
                "National Bank of Ukraine" : "National Bank of Ukraine",
                "NBU Governor" : "National Bank of Ukraine",
                "National Bank of North Macedonia" : "National Bank of North Macedonia",
                "Netherlands Bank" : "netherlands bank",
                "nederlandsche bank" : "netherlands bank",
                "Reserve Bank of Fiji" : "Reserve Bank of Fiji",
                "Reserve Bank of India" : "reserve bank of india",
                "Bank of India" : "reserve bank of india",
                "Reserve Bank of Malawi" : "Reserve Bank of Malawi",
                "Reserve Bank of New Zealand" : "Reserve Bank of New Zealand",
                "Reserve of the Bank of New Zealand" : "Reserve Bank of New Zealand",
                "Reserve Bank of Vanuatu" : "Reserve Bank of Vanuatu",
                "Saudi Arabian Monetary Agency" : "Saudi Arabian Monetary Agency",
                "South African Reserve Bank" : "south african reserve bank",
                "Bank of South Africa" : "south african reserve bank",
                "State Bank of Pakistan" : "State Bank of Pakistan",
                "Swiss National Bank" : "Swiss National Bank",
                "Banque nationale suisse" : "Swiss National Bank",
                "European Monetary Institute" : "European Monetary Institute",
                "Bank for International Settlements" : "Bank for International Settlements",
                "Nederlandsche Bank" : "Nederlandsche Bank",
                "Bank of China" : "people's bank of china",
                "People's Bank of China" : "people's bank of china",
                "Banque de France" : "Bank of France",
                "Bank of France" : "Bank of France",
                "Banque of France" : "Bank of France",
                "International Monetary Fund" : "International Monetary Fund",
                "National Bank of the Republic of Macedonia" : "national bank of north macedonia",
                "National Bank of the Republic of North Macedonia" : "national bank of north macedonia",
                "Bank of Turkey" : "central bank of the republic of turkey",
                "Central Bank of the Republic of Turkey" : "central bank of the republic of turkey",
                "Bank of Poland" : "Bank of Poland",
                "Reserve Bank of Australia" : "reserve bank of australia",
                "Australian Reserve Bank" : "reserve bank of australia",
                "Bank of Australia" : "reserve bank of australia"}

# List of cities found in the dataset that are the same. Mix of ChatGPT, Gemini and manually added duplicates
duplicate_cities = {
  "Jackson Hole": ["Jackson Hole", "Jackson Hole, Wyoming"],
  "Washington": ["Washington", "Washington, D.C.", "Washington DC", "Washington D.C.", "Washington, DC", "Washington, D C"],
  "New York": ["New York", "New York City", "New York, New York", "NY"],
  "Frankfurt": ["Frankfurt", "Frankfurt-am-Main", "Frankfurt am Main", "Frankfurt/Main", "Francfort"],
  "Delhi": ["Delhi", "New Delhi"],
  "Tokyo": ["Tokyo", "Tokio", "Toyko"],
  "Pittsburgh": ["Pittsburgh", "Pittsburgh, Pennsylvania"],
  "Boston": ["Boston", "Boston, USA", "Boston, Massachusetts"],
  "Annandale-on-Hudson": ["Annandale-on-Hudson", "Annandale-on-Hudson, New York", "Annandale-on-the-Hudson, New York"],
  "Phoenix": ["Phoenix", "Phoenix, Arizona"],
  "San Diego": ["San Diego", "San Diego, California"],
  "Geneva": ["Genève", "Geneva"],
  "Evanston": ["Evanston, Illinois", "Evanston"],
  "Arlington": ["Arlington", "Arlington, Virginia"],
  "Atlanta": ["Atlanta", "Atlanta, Georgia"],
  "Berkeley": ["Berkeley", "Berkeley, California"],
  "Montréal": ["Montreal", "Montréal", "Montreal, Quebec"],
  "Tel Aviv": ["Tel Aviv", "Tel-Aviv"],
  "Vienna": ["Vienna", "Wien"],
  "Basel": ["Basle", "Basel", "Basel, Switzerland"],
  "Zurich": ["Zurich", "Zürich"],
  "Kansas City": ["Kansas City", "Kansas City, Missouri"],
  "Cleveland": ["Cleveland", "Cleveland, Ohio"],
  "Luxembourg": ["Luxembourg", "Luxemburg"],
  "Philadelphia": ["Philadelphia", "Philadelphia, Pennsylvania"],
  "St. Louis": ["St. Louis", "St Louis", "St. Louis, Missouri", "St Louis, Missouri"],
  "Chicago": ["Chicago", "Chicago, Illinois"],
  "Ithaca": ["Ithaca", "Ithaca, New York"],
  "Malmö": ["Malmö", "Malmö and Kristianstad"],
  "Marrakesh": ["Marrakech", "Marrakesh"],
  "Ann Arbor": ["Ann Arbor", "Ann Arbor, Michigan"],
  "Orlando": ["Orlando", "Orlando, Florida"],
  "Halifax": ["Halifax", "Halifax, Nova Scotia"],
  "Charlottetown": ["Charlottetown", "Charlottetown, Prince Edward Island"],
  "Calgary": ["Calgary", "Calgary, Alberta"],
  "Québec City": ["Quebec", "Quebec City", "Quebec City, Quebec", "Québec City, Québec"],
  "Santa Barbara": ["Santa Barbara", "Santa Barbara, California"],
  "Columbus": ["Columbus", "Columbus, Ohio"],
  "Los Angeles": ["Los Angeles", "Los Angeles, California"],
  "Boca Raton": ["Boca Raton", "Boca Raton, Florida"],
  "Cambridge": ["Cambridge", "Cambridge, Massachusetts", "Cambridge MA"],
  "Charleston": ["Charleston", "Charleston, South Carolina"],
  "Nashville": ["Nashville", "Nashville, Tennessee"],
  "Las Vegas": ["Las Vegas", "Las Vegas, Nevada"],
  "London": ["London", "East London"],
  "Bombay": ["Bombay", "Mumbai"],
  "Calcutta": ["Calcutta", "Kolkata"],
  "Bangalore": ["Bangalore", "Bengaluru"],
  "Macau": ["Macau", "Macao", "Macao SAR"],
  "San Francisco": ["San Francisco", "San Francisco, California"],
  "Lexington": ["Lexington", "Lexington, Virginia", "Lexington, Kentucky"],
  "Stanford": ["Stanford", "Stanford, California", "Stanford, CA"],
  "Raleigh": ["Raleigh", "Raleigh, North Carolina"],
  "Charlotte": ["Charlotte", "Charlotte, North Carolina"],
  "Minneapolis": ["Minneapolis", "Minneapolis, Minnesota"],
  "Tallinn": ["Tallinn", "Tallin", "Tallinn, Estonia"],
  "St. Kitts": ["Saint Christopher (St Kitts) and Nevis", "St. Kitts"],
  "Brussels": ["Brussels", "Bruxelles"],
  "Edinburgh": ["Edinburgh", "Edinburg"],
  "Honolulu": ["Honolulu", "Honolulu, Hawaii"],
  "Amsterdam": ["Amsterdam", "Amsterdan"],
  "Montreal": ["Montreal", "Montreal, Quebec", "Montréal", "Montréal, Quebec"],
  "Venice": ["Venice", "Venice, Italy"],
  "Mexico City": ["Mexico City", "Mexico City, Mexico"],
  "Makati": ["Makati City", "Makati", "Makaty City"],
  "East Lansing": ["East Lansing, Michigan", "East Lansing"],
  "Aspen": ["Aspen", "Aspen, Colorado"],
  "Geneva": ["Geneva", "Genève"],
  "Hamburg": ["Hamburg", "Hamburg, Germany"],
  "Portland": ["Portland", "Portland, Oregon"],
  "Reykjavik": ["Reykjavik", "Reykjavìk", "Reykjavík"],
  "Toronto": ["Toronto", "Toronto, Ontario"],
  "St. Gallen": ["St Gallen", "St. Gallen"],
  "Ottawa": ["Ottawa", "Otttawa", "Ottawa, Ontario"],
  "Santiago": ["Santiago, Chile", "Santiago de Chile"],
  "Vancouver": ["Vancouver", "Vancouver, British Columbia"],
  "Victoria": ["Victoria", "Victoria, British Columbia"],
  "Waterloo": ["Waterloo", "Waterloo, Ontario"],
  "Newark": ["Newark", "Newark, DE"],
  "Richmond": ["Richmond", "Richmond, Virginia"],
  "Rochester": ["Rochester", "Rochester, New York", "Rochester, NY"],
  "Banff": ["Banff, Alberta", "Banff"],
  "White Sulphur Springs": ["White Sulphur Springs", "White Sulphur Springs, West Virginia"],
  "Colorado Springs": ["Colorado Springs", "Colorado Springs, Colorado"],
  "Cernobbio": ["Cernobbio", "Cernobbio, Italy"],
  "San Diego": ["San Diego", "San Diego, California"],
  "Santa Fe": ["Santa Fe", "Santa Fe, New Mexico"],
  "St. John's": ["St. John's", "St. John's, Newfoundland and Labrador"],
  "Saint Julian's" : ["Saint Julian", "Saint Julian's", "Saint Julian s", "St. Julian¿s"],
  "Sydney": ["Sydney", "Sydney, Australia"],
  "Tampa": ["Tampa", "Tampa, Florida"],
  "Tokyo": ["Tokyo", "Tokio", "Toyko"],
  "Winnipeg": ["Winnipeg", "Winnipeg, Manitoba"],
  "Willemstad" : ["Willemstad, Curaçao, Netherlands Antilles", "Willemstad", "Willemstad, Curacao"],
  "Zurich": ["Zurich", "Zürich"],
  "Las Vegas": ["Las Vegas", "Las Vegas, Nevada"],
  "Los Angeles": ["Los Angeles", "Los Angeles, California"],
  "Phoenix": ["Phoenix", "Phoenix, Arizona"],
  "San Francisco": ["San Francisco", "San Francisco, California"],
  "Chicago": ["Chicago", "Chicago, Illinois"],
  "Dallas": ["Dallas", "Dallas, Texas"],
  "Denver": ["Denver", "Denver, Colorado"],
  "Miami": ["Miami", "Miami Beach", "Miami, Florida"],
  "Orlando": ["Orlando", "Orlando, Florida"],
  "Online": ["virtual", "online", "virtual event", "Virtual Event", "webcast", "Virtual event", "online workshop", "Virtual"],
  "St. Augustine": ["St Augustine", "St. Augustine"],
  "Palm Beach": ["Palm Beach, Florida", "Palm Beach"],
  "Dayton": ["Dayton", "Dayton, Ohio"],
  "New Haven": ["New Haven", "New Haven, USA", "New Haven, Connecticut", "New Haven CT, USA"],
  "Aix-en-Provence": ["Aix-en-Provence", "Aix en Provence"],
  "Victoria": ["Victoria", "Victoria, British Columbia"],
  "Baden-Baden": ["Baden Baden", "Baden-Baden"],
  "Hanover": ["Hanover, New Hampshire", "Hanover"],
  "Montreal": ["Montréal", "Montréal, Quebec"],
  "East Lansing": ["East Lansing, Michigan", "East Lansing"],
}

duplicate_names = {
  "Philip R Lane": ["Philip R Lane", "Philip R. Lane"],
  "Villy Bergström": ["Mr Villy Bergström", "Villy Bergström"],
  "Tony Latter": ["Mr Tony Latter", "Tony Latter"],
  "Ernst Welteke": ["Mr Ernst Welteke", "Ernst Welteke"],
  "Einars Repse": ["Einars Repse", "Einar Repse"],
  "Martín Redrado": ["Martín Redrado", "Martin Redrado", "Martìn Redrado"],
  "Zhou Xiaochuan": ["Zhou Xiaochuan", "Zhou Xiaochuann"],
  "Lim Hng Kiang": ["Mr Lim Hng Kiang", "Lim Hng Kiang"],
  "Thirachai Phuvanatnaranubala": ["Thirachai Phuvanat naranubala", "Thirachai Phuvanatnaranubala"],
  "Zamani Abdul Ghani": ["Datuk Zamani Abdul Ghani", "Zamani Abdul Ghan", "Zamani Abdul Ghani"],
  "Charles Soludo": ["Charles Chukwuma Soludo", "Charles C Soludo"],
  "Ewart Williams": ["Ewart S Williams", "Ewart Williams"],
  "Zamani Abdul Ghani": ["Zamani Abdul Ghani", "Zamani Abdul Ghan"],
  "Emsley Tromp": ["Emsley D Tromp", "Emsley Tromp"],
  "Hermann Remsperger": ["Hermann Remsperger", "Hermann Remsperge"],
  "Andrew Large": ["Sir Andrew Large", "Andrew Large"],
  "Krzysztof Rybinski": ["Krzysztof Rybinski", "Krzysztof Rybiñski"],
  "José Manuel González-Páramo": ["José Manuel González-Páramo", "Jose Manuel Gonzalez-Paramo"],
  "Miguel Fernandez Ordonez": ["Miguel Fernández Ordóñez", "Miguel Fernandez Ordonez"],
  "Rannveig Sigurðardóttir": ["Rannveig Sigurdardóttir", "Rannveig Sigurðardóttir"],
  "Loi Bakani": ["Loi M Bakani", "Loi Bakani"],
  "Norman Chan": ["Norman T L Chan", "Norman Chan"],
  "Benny Popoitai": ["Benny BM Popoitai", "Benny Popoitai"],
  "Susan Schmidt Bies": ["Susan Schmidt Bies", "Susan S Bies"],
  "Nicholas C Garganas": ["Mr Nicholas C Garganas", "Nicholas C Garganas"],
  "Zeti Akhtar Aziz": ["Zeti Akhtar Aziz", "Zeti Akhtar Aziz"],
  "Martín Redrado": ["Martín Redrado", "Martin Redrado", "Martìn Redrado"],
  "Kishori Udeshi": ["Kishori J Udeshi", "Kishori Udeshi"],
  "Wu Xiaoling": ["Wu Xiaoling", "Wu Xiaolin"],
  "Nor Shamsiah Mohd Yunus": ["Nor Shamsiah Mohd Yunus", "Tan Sri Nor Shamsiah Mohd Yunus"],
  "Gediminas Šimkus": ["Gediminas Šimkus", "Gediminas Simkus"],
  "Anita Angelovska Bezoska": ["Anita Angelovska-Bezoska", "Anita Angelovska Bezoska", "Anita Angelovska Bezhoska"],
  "José Darío Uribe": ["José Darío Uribe Escobar", "José Darío Uribe"],
  "Sanusi Lamido Sanusi": ["Mallam Sanusi Lamido Sanusi", "Sanusi Lamido Sanusi"],
  "Timothy Geithner": ["Timothy F Geithner", "Timothy Geithner"],
  "Vítor Constâncio": ["Vitor Constâncio", "Vítor Constâncio"],
  "Gediminas Simkus": ["Gediminas Šimkus", "Gediminas Simkus"],
  "Adnan Zaylani Mohamad Zahid": ["Encik Adnan Zaylani Mohamad Zahid", "Adnan Zaylani Mohamad Zahid"],
}
